force-app/main/default/objects/IndiaPoll__c/IndiaPoll__c.object-meta.xml
<CustomObject>
    <label>IndiaPoll</label>
    <nameField>
        <label>India Poll Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IndiaPolls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IndiaPoll__c/fields/IndiaState__c.field-meta.xml
<CustomField>
    <fullName>IndiaState__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IndiaState</label>
    <referenceTo>IndiaState__c</referenceTo>
    <relationshipLabel>IndiaPolls</relationshipLabel>
    <relationshipName>IndiaPolls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IndiaPoll__c/fields/Phase_Name__c.field-meta.xml
<CustomField>
    <fullName>Phase_Name__c</fullName>
    <label>Phase Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IndiaPoll__c/fields/Poll_Date__c.field-meta.xml
<CustomField>
    <fullName>Poll_Date__c</fullName>
    <label>Poll Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IndiaState__c/IndiaState__c.object-meta.xml
<CustomObject>
    <label>IndiaState</label>
    <nameField>
        <label>IndiaState Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IndiaStates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IndiaState__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <label>State Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP</fullName>
                <default>true</default>
                <label>AP</label>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>KA</fullName>
            </value>
            <value>
                <fullName>KE</fullName>
            </value>
            <value>
                <fullName>MP</fullName>
            </value>
            <value>
                <fullName>TN</fullName>
            </value>
            <value>
                <fullName>TS</fullName>
            </value>
            <value>
                <fullName>UP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IndiaPollController.cls
public with sharing class IndiaPollController {
    
    @AuraEnabled
    public static List<IndiaPoll__c> showData(){
        try {
            
            List<IndiaPoll__c> ilist=[select Name,IndiaState__r.State_Name__c,Phase_Name__c,Poll_Date__c
                                    from IndiaPoll__c order by Name];
                                return ilist;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string deletePoll(String pollid){
        try {

            IndiaPoll__c ip = [select Name from IndiaPoll__c where Id = :pollid];
            String pollname = ip.Name;

            Database.delete(ip);
            return 'Poll Data with number '+pollname+' is been deleted';
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}